config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # MUSIC RADIO DASHBOARD
  root                             to: "music_radios#dashboard"
  get '/',                         to: 'music_radios#dashboard',  as: 'dashboard'


  # LANDING PAGE FOR NEW USERS
  get '/get',                      to: 'static_pages#landing',    as: 'landing'

  # Login Page
  get '/start-your-jounce',        to: 'static_pages#login_page', as: 'login_page'


  # PREMIUM STATUS

  # SECURE PAYMENT PAGE
  get '/secure_pay',               to: 'static_pages#secure_pay', as: 'secure_pay'

  # SUCCESSFUL PAYMENT
  get 'register_premium',          to: 'static_pages#register_premium', as: 'register_premium'

  # UNSUBSCRIBE
  get 'unsubscribe_from_premium',  to: 'static_pages#unsubscribe_from_premium', as: 'unsubscribe_from_premium'


  # USER AUTHENTICATION
  get 'login_as_guest', to: 'sessions#create_guest_session',    via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create',    via: [:get, :post]
  match 'auth/failure',            to: redirect('/landing'), via: [:get, :post]
  match 'signout',                 to: 'sessions#destroy',        as: 'signout', via: [:get, :post]










  namespace :api, defaults: {format: :json} do
    # USER AUTHENTICATION
    resource :session, only: [:destroy]

    # RADIOS
    get 'get_radio_songs',     to: 'radio_songs#retrieveUpcomingSongs', as: 'get_additional_songs_for_radio'

    # PLAYLISTS
    post 'create_playlist',      to: 'playlists#create', as: 'create_playlist'
    get 'view_playlist',     to: 'playlists#show', as: 'playlist_show'

    # PLAYLIST SONGS
    post 'create_playlist_song',      to: 'playlist_songs#create', as: 'create_playlist_song'
    delete 'destroy_playlist_song',   to: 'playlist_songs#destroy', as: 'destroy_playlist_song'


    # SONG LIKES
    post    'create_song_like',             to: 'song_likes#create',  as: 'create_song_like'
    delete 'destroy_song_like',             to: 'song_likes#destroy', as: 'destroy_song_like'
    get 'view_current_user_song_likes',     to: 'song_likes#show',    as: 'current_user_song_likes_index'


    # SONG RATINGS
    patch 'set_song_rating',     to: 'song_ratings#update', as: 'declare_song_rating'

    # ALBUM
    get 'view_album',      to: 'albums#show', as: 'album_show'

    # ARTIST
    get 'view_artist',     to: 'artists#show', as: 'artist_show'

    # ALBUM LIKES
    get 'followed_albums_for_current_user',     to: 'album_likes#index', as: 'get_followed_albums'
    post    'create_album_like',  to: 'album_likes#create', as: 'create_album_like'
    delete 'destroy_album_like',  to: 'album_likes#destroy', as: 'destroy_album_like'

    # ARTIST LIKES
    get 'followed_artists_for_current_user',     to: 'artist_likes#index', as: 'get_followed_artists'
    post    'create_artist_like',   to: 'artist_likes#create',  as: 'create_artist_like'
    delete  'destroy_artist_like',  to: 'artist_likes#destroy', as: 'destroy_artist_like'

    # FRIENDSHIPS
    post    'create_friendship',             to: 'friendships#create',  as: 'create_friendship'
    delete 'destroy_friendship',             to: 'friendships#destroy', as: 'destroy_friendship'


    # SOCIAL CONTENT
    get 'social_content',     to: 'friendships#social_content', as: 'social_content'

    # SEARCH RESULTS
    get 'search_results',     to: 'search_results#retrieve',    as: 'get_search_results'

    # FEATURED CONTENT
    get 'featured_content',   to: 'featured_contents#retrieve', as: 'get_featured_content'

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_to_login_page_unless_logged_in, only: [:secure_pay, :register_premium]
  before_action :redirect_to_music_player_dashboard_if_already_logged_in, only: [:login_page]


  def landing
    render layout: "landing"
  end

  def secure_pay
    render layout: "secure_pay"
  end

  def login_page
    render :login, layout: false
  end

  def register_premium
    @user = current_user
    @user.is_premium = true
    @user.save
    redirect_to dashboard_url
  end

  def unsubscribe_from_premium
    @user = current_user
    @user.is_premium = false
    @user.save
    redirect_to landing_url
  end

end

app/views/static_pages/landing.html.erb
<header class="header">
  <nav class="header-nav clearfix">

    <h1 class="header-logo">
      <a href="/">Jounce Streaming<br /> Music Radio</a>
    </h1>

    <ul class="header-list clearfix">
      <% if current_user %>
        <li><a href="<%= signout_url %>">Logout</a></li>
      <% else %>
        <li><a href="<%= login_page_url %>">Login</a></li>
      <% end %>
      <% if current_user && current_user.is_premium %>
      <li><a href="<%=unsubscribe_from_premium_url %>">Unsubscribe</a></li>
      <% else %>
      <li><a href="<%=secure_pay_url %>">Go Premium</a></li>
      <% end %>
      <li><a href="#">Language</a></li>
      <li><a href="#">Settings</a></li>
    </ul>

  </nav>
</header>

<div id="image-filter"></div>


<main class="content clearfix">
  <div id="video-backing">
    <video id="commercial-video" controls preload autoplay height="100%" loop>
      <source src="https://s3.amazonaws.com/odla/video/Jounce+Commercial.mp4" type="video/mp4">
      Your browser does not support HTML5 video.
    </video>
  </div>


  <div id="informational-text">
    <div id="finally-text">
      Finally,
    </div>

    <div id="jounce-info-text">
      Jounce
    </div>
    <div id="jounce-free-text">
      Free.
    </div>






    <a id="sign_in" href="<%= login_as_guest_url %>" title="" class="oauth-login">
      <span class="oauth-login__text">Start Now&nbsp;&nbsp;<br/>

      No Signup Required.</span>
    </a>
  </div>


  </div>




</main>

app/views/static_pages/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" type="image/png" href="<%= image_url("icon.png") %>"/>
  <title>Jounce Streaming Music Radio</title>
  <%= stylesheet_link_tag    'login_page', media: 'all' %>
  <%= javascript_include_tag 'jQuery' %>
  <%= javascript_include_tag 'login_page' %>
  <%= csrf_meta_tags %>
</head>
<body class="clearfix">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <div id="background">

  </div>

  <div class="container" id="form-container">
    <div id="Checkout" class="inline">




        <!-- <h1>Your <span id="next-title-span">Next</span> <span id="jounce-title-span">Jounce</span><br/>

        Starts <span id="now-title-span">Now</span></h1> -->
        <h1>Don't let <span id="now-title-span">anyone</span> stand in the way of your <span id="next-title-span">Jounce</span>
          <!-- <span id="jounce-title-span">Jounce</span><br/> -->

        <!-- Starts <span id="now-title-span">Now</span> -->
      </h1>
        <form>
          <div id="standard-login-box">
            <div class="form-group">
                <label for="Email">Email</label>
                <input id="Email" class="form-control" type="text" maxlength="255"></input>
            </div>
            <div class="form-group">
                <label for="Password">Password</label>
                <input id="Password" class="null card-image form-control" type="password"></input>
            </div>

            <button id="LoginButton" class="btn btn-block btn-success submit-button" type="submit">
                <span class="submit-button-lock lined-content"></span>
                <span class="align-middle lined-content">Log In</span>
            </button>
          </div>





          <div id="vertical-divider">
          </div>





          <div id="social-login-box" >
            <svg xmlns="http://www.w3.org/2000/svg" display="none">
              <defs>
                <symbol id="icon-facebook--f" viewBox="0 0 100 100">
                  <path d="M69 100V61.3h13l1.9-15.1H69v-9.6c0-4.4 1.2-7.3 7.5-7.3h8V15.7c-1.4-.2-6.1-.6-11.6-.6-11.5 0-19.4 7-19.4 19.9v11.1h-13v15.1h13V100H69z"/>
                </symbol>
              </defs>
            </svg>

            <a id="sign_in" href="<%= root_url %>auth/facebook" title="" class="oauth-login">
              <svg class="oauth-login__icon">
                <use xlink:href="#icon-facebook--f"></use>
              </svg>
              <span class="oauth-login__text">
                Login with facebook.
              </span>
            </a>
          </div>

















          </div>
        </form>
    </div>
  </div>


</body>
</html>

app/views/static_pages/secure_pay.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<div class="container" id="form-container">
  <div id="Checkout" class="inline">
      <h1>Go Premium</h1>
      <div class='card-wrapper'></div>
      <div class="card-row">
          <span class="visa"></span>
          <span class="mastercard"></span>
          <span class="amex"></span>
          <span class="discover"></span>
      </div>
      <form>
          <div class="form-group">
              <label for="PaymentAmount">Payment amount</label>
              <div class="amount-placeholder">
                  <span class="lined-content">$</span>
                  <span class="lined-content">9.99<span class="disclaimer lined-content">&nbsp;&nbsp;(recurring payments billed monthly)</span></span>
              </div>
          </div>
          <div class="form-group">
              <label for="NameOnCard">Name on card</label>
              <input id="NameOnCard" class="form-control" type="text" maxlength="255"></input>
          </div>
          <div class="form-group">
              <label for="CreditCardNumber">Card number</label>
              <input id="CreditCardNumber" class="null card-image form-control" type="text"></input>
          </div>
          <div class="expiry-date-group form-group">
              <label for="ExpiryDate">Expiry date</label>
              <input id="ExpiryDate" class="form-control" type="text" placeholder="MM / YY" maxlength="7"></input>
          </div>
          <div class="security-code-group form-group">
              <label for="SecurityCode">Security code</label>
              <div class="input-container" >
                  <input id="SecurityCode" class="form-control" type="text" ></input>
                  <i id="cvc" class="fa fa-question-circle"></i>
              </div>
              <!-- <div class="cvc-preview-container two-card hide">
                  <div class="amex-cvc-preview"></div>
                  <div class="visa-mc-dis-cvc-preview"></div>
              </div> -->
          </div>
          <div class="zip-code-group form-group">
              <label for="ZIPCode">ZIP/Postal code</label>
              <div class="input-container">
                  <input id="ZIPCode" class="form-control" type="text" maxlength="10"></input>
                  <a tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-placement="left" data-content="Enter the ZIP/Postal code for your credit card billing address."><i class="fa fa-question-circle"></i></a>
              </div>
          </div>
          <button id="PayButton" class="btn btn-block btn-success submit-button" type="submit">
              <span class="submit-button-lock lined-content"></span>
              <span class="align-middle lined-content">Pay $9.99</span>
          </button>
          <div id="handled-by-stripe"><b class="lined-content">Secure Payment Handled By &nbsp;</b><a target="_blank" class="lined-content" href="https://stripe.com/docs/testing#cards"><i class="fa fa-cc-stripe fa-2x lined-content" aria-hidden="true"></i></a></div>
      </form>
  </div>
</div>

<script>
  window.dashboard_url = "<%= register_premium_url %>";
</script>