config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # MUSIC RADIO DASHBOARD
  root                             to: "music_radios#dashboard"
  get '/',                         to: 'music_radios#dashboard',  as: 'dashboard'


  # LANDING PAGE FOR NEW USERS
  get '/get',                      to: 'static_pages#landing',    as: 'landing'

  # Login Page
  get '/start-your-jounce',        to: 'static_pages#login_page', as: 'login_page'


  # PREMIUM STATUS

  # SECURE PAYMENT PAGE
  get '/secure_pay',               to: 'static_pages#secure_pay', as: 'secure_pay'

  # SUCCESSFUL PAYMENT
  get 'register_premium',          to: 'static_pages#register_premium', as: 'register_premium'

  # UNSUBSCRIBE
  get 'unsubscribe_from_premium',  to: 'static_pages#unsubscribe_from_premium', as: 'unsubscribe_from_premium'


  # USER AUTHENTICATION
  get 'login_as_guest', to: 'sessions#create_guest_session',    via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create',    via: [:get, :post]
  match 'auth/failure',            to: redirect('/landing'), via: [:get, :post]
  match 'signout',                 to: 'sessions#destroy',        as: 'signout', via: [:get, :post]










  namespace :api, defaults: {format: :json} do
    # USER AUTHENTICATION
    resource :session, only: [:destroy]

    # RADIOS
    get 'get_radio_songs',     to: 'radio_songs#retrieveUpcomingSongs', as: 'get_additional_songs_for_radio'

    # PLAYLISTS
    post 'create_playlist',      to: 'playlists#create', as: 'create_playlist'
    get 'view_playlist',     to: 'playlists#show', as: 'playlist_show'

    # PLAYLIST SONGS
    post 'create_playlist_song',      to: 'playlist_songs#create', as: 'create_playlist_song'
    delete 'destroy_playlist_song',   to: 'playlist_songs#destroy', as: 'destroy_playlist_song'


    # SONG LIKES
    post    'create_song_like',             to: 'song_likes#create',  as: 'create_song_like'
    delete 'destroy_song_like',             to: 'song_likes#destroy', as: 'destroy_song_like'
    get 'view_current_user_song_likes',     to: 'song_likes#show',    as: 'current_user_song_likes_index'


    # SONG RATINGS
    patch 'set_song_rating',     to: 'song_ratings#update', as: 'declare_song_rating'

    # ALBUM
    get 'view_album',      to: 'albums#show', as: 'album_show'

    # ARTIST
    get 'view_artist',     to: 'artists#show', as: 'artist_show'

    # ALBUM LIKES
    get 'followed_albums_for_current_user',     to: 'album_likes#index', as: 'get_followed_albums'
    post    'create_album_like',  to: 'album_likes#create', as: 'create_album_like'
    delete 'destroy_album_like',  to: 'album_likes#destroy', as: 'destroy_album_like'

    # ARTIST LIKES
    get 'followed_artists_for_current_user',     to: 'artist_likes#index', as: 'get_followed_artists'
    post    'create_artist_like',   to: 'artist_likes#create',  as: 'create_artist_like'
    delete  'destroy_artist_like',  to: 'artist_likes#destroy', as: 'destroy_artist_like'

    # FRIENDSHIPS
    post    'create_friendship',             to: 'friendships#create',  as: 'create_friendship'
    delete 'destroy_friendship',             to: 'friendships#destroy', as: 'destroy_friendship'


    # SOCIAL CONTENT
    get 'social_content',     to: 'friendships#social_content', as: 'social_content'

    # SEARCH RESULTS
    get 'search_results',     to: 'search_results#retrieve',    as: 'get_search_results'

    # FEATURED CONTENT
    get 'featured_content',   to: 'featured_contents#retrieve', as: 'get_featured_content'

  end

end

app/controllers/music_radios_controller.rb
class MusicRadiosController < ApplicationController
  include RadioAlgorithms

  before_action :redirect_to_landing_page_unless_logged_in, only: [:dashboard]

  def dashboard
    @initial_songs_for_radio = get_songs_for_radio
    @information_on_group_of_initial_song_list = {
      type: "Radio",
      radio_station_name: "Jounce Music Radio",
      radio_id: 1
    }
    render layout: "dashboard"
  end

end

app/views/music_radios/_dashboard_bootstrapper.html.erb
<script>

window.currentUser = {
  username:          "<%= current_user.username %>",
  profile_image_url: "<%= current_user.profile_image_url %>",
  isPremium:         <%= current_user.is_premium %>,
};


window.applicationRoutes = {
  signoutRoute:                                 "<%= api_session_url %>",
  landingPageRoute:                             "<%= landing_url %>",

  securePayRoute:                               "<%= secure_pay_url %>",


  createPlaylistRoute:                          "<%= api_create_playlist_url %>",


  createSongLikeRoute:                          "<%= api_create_song_like_url %>",
  destroySongLikeRoute:                         "<%= api_destroy_song_like_url %>",

  declareSongRatingRoute:                       "<%= api_declare_song_rating_url %>",

  getFollowedAlbumsRoute:                       "<%= api_get_followed_albums_url %>",

  getFollowedArtistsRoute:                      "<%= api_get_followed_artists_url %>",

  albumShowRoute:                               "<%= api_album_show_url %>",

  artistShowRoute:                              "<%= api_artist_show_url %>",


  createAlbumLikeRoute:                         "<%= api_create_album_like_url %>",
  destroyAlbumLikeRoute:                        "<%= api_destroy_album_like_url %>",

  createArtistLikeRoute:                         "<%= api_create_artist_like_url %>",
  destroyArtistLikeRoute:                        "<%= api_destroy_artist_like_url %>",


  getSocialContentRoute:                        "<%= api_social_content_url %>",

  playlistShowRoute:                            "<%= api_playlist_show_url %>",

  songsLikedByCurrentUserShowRoute:             "<%= api_current_user_song_likes_index_url %>",


  createFriendshipRoute:                        "<%= api_create_friendship_url %>",
  destroyFriendshipRoute:                       "<%= api_destroy_friendship_url %>",

  createPlaylistSongRoute:                      "<%= api_create_playlist_song_url %>",
  destroyPlaylistSongRoute:                     "<%= api_destroy_playlist_song_url %>",


  retrieveAdditionalSongsForRadioRoute:         "<%= api_get_additional_songs_for_radio_url %>",



  retrieveSearchResultsRoute:                   "<%= api_get_search_results_url %>",

  retrieveFeaturedContentRoute:                 "<%= api_get_featured_content_url %>",



};
window.playlistNamesOnLoad = <%= raw current_user.playlists.map { |playlist| {name: playlist.name, id: playlist.id} }.to_json %>;

window.friendsListOnLoad =
  <% friends = current_user.friends %>
  <%  followed_friends_information = friends.map do |friend| %>

  <%  information_on_last_song_listened_to = friend.information_on_last_song_listened_to %>
  <%  {id:                                      friend.id, %>
  <%   username:                                friend.username, %>
  <%   profile_image_url:                       friend.profile_image_url, %>
  <%   email:                                   friend.email, %>
  <%   id_of_last_song_listened_to:             information_on_last_song_listened_to[:song_id], %>
  <%   title_of_last_song_listened_to:          information_on_last_song_listened_to[:song_title], %>
  <%   id_of_album_of_last_song_listened_to:    information_on_last_song_listened_to[:album_id], %>
  <%   title_of_album_of_last_song_listened_to: information_on_last_song_listened_to[:album_title], %>
  <%   id_of_artist_of_last_song_listened_to:   information_on_last_song_listened_to[:artist_id], %>
  <%   name_of_artist_of_last_song_listened_to: information_on_last_song_listened_to[:artist_name] %>
  <%  } %>
  <% end %>
  <%= raw followed_friends_information.to_json %>;

window.initialSongsToLoadForRadio =
  <% songs =  @initial_songs_for_radio %>
  <% information_for_initial_songs = songs.map do |song| %>
    <% { %>
        <% song_id:          song.id, %>
        <% path:             song.path, %>
        <% title:            song.title, %>
        <% artist_id:        song.artist.id, %>
        <% artist_name:      song.artist.name, %>
        <% album_id:         song.album.id, %>
        <% album_title:      song.album.title, %>
        <% star_rating:      SongRating.get_rating_by_user_and_song(current_user, song), %>
        <% duration:         song.duration, %>
        <% is_followed:      song.is_followed_by?(current_user), %>
        <% album_cover_path: song.album.album_cover_path %>
    <% } %>
  <% end %>
  <%= raw information_for_initial_songs.to_json %>
;

window.informationOnGroupOfInitialSongsToLoadForRadio = <%= raw @information_on_group_of_initial_song_list.to_json  %>;


</script>

app/views/music_radios/dashboard.html.erb
<div id="content" class="root">
  To enjoy Jounce Streaming Music Radio, it is necessary to enable JavaScript.<br/>
  Here are some easy-to-follow <a href="http://www.enable-javascript.com/" target="_blank" style="display: inline; text-decoration: underline; color: #417eaf; font-weight: bold;"> instructions on how to enable JavaScript in your web browser</a>.
</div>